before_script: source ./ci/jruby_download_commons_compress.sh
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: ruby-head
